<a href="https://colab.research.google.com/github/tselane2110/Urdu-BinarySarcasmDetection/blob/main/TF_IDF_logisticRegressionModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0. Cloning into Git Repo

In [1]:
# cloning into Git Repo
!git clone https://github.com/tselane2110/NaturalLanguageProcessing

Cloning into 'NaturalLanguageProcessing'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 50 (delta 22), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (50/50), 1.44 MiB | 3.87 MiB/s, done.
Resolving deltas: 100% (22/22), done.

In [2]:

%cd /content/NaturalLanguageProcessing

/content/NaturalLanguageProcessing

In [3]:
%ls

projectGuidelines.pdf  TF_IDF_logisticRegressionModel.ipynb
README.md              urdu_sarcastic_dataset.csv

## 1. Data Analysis and Preprocessing

In [4]:
import re
import matplotlib.pyplot as plt
import pandas as pd

pd.set_option('display.max_colwidth', None)   # show full column width
df = pd.read_csv('urdu_sarcastic_dataset.csv')
df.head()

,urdu_text,is_sarcastic,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,🤣😂😂 ہو لینے دے میری شادی فسادن ٹھیک ہے کوجی نہیں چاہیے 😐😐😐🤣,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,چل مہمانوں میں کھانا سرو کر چڑیل چاچی نوں دسدی آں میں😂😂,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,کامران خان آپکی دن بھریہ زمہ داری لگائی گئی اپوزیشن کی کردار کشی اوراس پربھونکناہےآپ خوشامدگری وچاپلوسی سےاورکتنی دولت کماناچاہتےہیں موٹرسائیکل سےپیجارو پراڈو تک کےسفرمیں ضمیرکی لاش سےاٹھتی بدبوآپ کی ناک بند نہیں کرتی ہے 🙏نوٹ آپ سب سےالتجاگزارش ہےہمیں بھی فالوکریں شکریہ,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,نہیں پائین 😎,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,`` مراد علی شاہ کے بھیس میں ڈی جی آئی ایس آئی تھے '' حامد میر😁,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['urdu_text', 'is_sarcastic', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

### i. Not Including Unnecessary Columns

In [6]:
# not using the extra unimportant columns

df = df.iloc[:, :-6]
df.head(10)

,urdu_text,is_sarcastic
0,🤣😂😂 ہو لینے دے میری شادی فسادن ٹھیک ہے کوجی نہیں چاہیے 😐😐😐🤣,1.0
1,چل مہمانوں میں کھانا سرو کر چڑیل چاچی نوں دسدی آں میں😂😂,1.0
2,کامران خان آپکی دن بھریہ زمہ داری لگائی گئی اپوزیشن کی کردار کشی اوراس پربھونکناہےآپ خوشامدگری وچاپلوسی سےاورکتنی دولت کماناچاہتےہیں موٹرسائیکل سےپیجارو پراڈو تک کےسفرمیں ضمیرکی لاش سےاٹھتی بدبوآپ کی ناک بند نہیں کرتی ہے 🙏نوٹ آپ سب سےالتجاگزارش ہےہمیں بھی فالوکریں شکریہ,0.0
3,نہیں پائین 😎,0.0
4,`` مراد علی شاہ کے بھیس میں ڈی جی آئی ایس آئی تھے '' حامد میر😁,1.0
5,قابل اعتبار ہی اکثر قاتل اعتبار ہوتے ہیں 💔🔥,1.0
6,انساں کو تھکا دیتا ہے سوچوں کا سفر بھی ... 🍁🥀,0.0
7,حامد میر صاحب ویلڈن👏😊,0.0
8,یار وچارہ ویلا ہوندا ہے اس آرے لگا ہویا ہے😂😂 تسی تے پکے نجومی ہو اسی منندے ہاں,1.0
9,یہ سمجھتے ہیں سارا پاکستان بیوقوف ھے 😂😂😂,1.0

In [7]:
# renaming the text columns
df = df.rename(columns={'urdu_text': 'text'})
df.head(2)

                                                          text  is_sarcastic
0  🤣😂😂 ہو لینے دے میری شادی فسادن ٹھیک ہے کوجی نہیں چاہیے 😐😐😐🤣           1.0
1      چل مہمانوں میں کھانا سرو کر چڑیل چاچی نوں دسدی آں میں😂😂           1.0

### ii. Dropping NaN rows

In [8]:
# finding NaN rows

df.isna().sum()

text            105
is_sarcastic     56
dtype: int64

In [9]:
# dropping all NaN rows

df = df.dropna()

In [10]:
df.head(2)

                                                          text  is_sarcastic
0  🤣😂😂 ہو لینے دے میری شادی فسادن ٹھیک ہے کوجی نہیں چاہیے 😐😐😐🤣           1.0
1      چل مہمانوں میں کھانا سرو کر چڑیل چاچی نوں دسدی آں میں😂😂           1.0

### iii. Converting DataType from Float to Int of `is_sarcastic` Column

In [11]:
# converting the datatype of is_sarcastic from float to int

df['is_sarcastic'] = df['is_sarcastic'].astype(int)
df.head(2)

                                                          text  is_sarcastic
0  🤣😂😂 ہو لینے دے میری شادی فسادن ٹھیک ہے کوجی نہیں چاہیے 😐😐😐🤣             1
1      چل مہمانوں میں کھانا سرو کر چڑیل چاچی نوں دسدی آں میں😂😂             1

### iv. Detecting and Analyzing Hashtag Content

In [12]:
import re
from collections import Counter

# extract all hashtags (lowercased) across all rows
hashtags = df['text'].str.findall(r'#(\w+)', flags=re.IGNORECASE)

# flatten and count
counter = Counter(
    tag.lower()
    for tags in hashtags
    for tag in tags
)

hashtag_counts = dict(counter)

In [13]:
len(hashtag_counts)

551

In [14]:
hashtag_df = pd.DataFrame(
    hashtag_counts.items(),
    columns=['hashtag', 'count']
)

In [15]:
hashtag_df = hashtag_df.sort_values('count', ascending=False).reset_index(drop=True)

In [16]:
hashtag_df.head(551)

             hashtag  count
0            sarcasm    391
1                طنز    163
2          sarcastic     57
3    آئےناں_کنٹینرتے     31
4               مزاح     22
..               ...    ...
546              tmc      1
547              bjp      1
548     lighthearted      1
549   خوش_مزاج_مولوی      1
550     اسلامی_لطائف      1

[551 rows x 2 columns]

### v. Text Cleaning

* Removed the following content:

  * URLs
  * @mentions
  * Hashtag contents that could leak the target label, for example #sarcasm, #sarcastic, #طنز etc. These were selected after carefully analyzing all hashtags that were present in the originally given dataset.

* Added \<EMPHASIS\>\<\EMPHASIS\> around the bold text
* Normalized Whitespaces
* Used `wordsegment` library to segment out the joint english words like goodmorningpakistan or HelloWorld would be converted to "good morning pakistan" and "hello world"
* Demojized emojis continue to keep the underscore in their name_tag

In [17]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.16.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.16.0-py3-none-any.whl (610 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 kB 10.3 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.16.0

In [18]:
!pip install wordsegment

Collecting wordsegment
  Downloading wordsegment-1.3.1-py2.py3-none-any.whl.metadata (7.7 kB)
Downloading wordsegment-1.3.1-py2.py3-none-any.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 35.3 MB/s eta 0:00:00
Installing collected packages: wordsegment
Successfully installed wordsegment-1.3.1

#### a. Helper Functions

In [19]:
import re
import emoji
import pandas as pd
import string
import unicodedata
from wordsegment import load, segment

load() # Load the English dictionaries for segmentation

URL_PATTERN = re.compile(r'(?:https?://|www\.)[^\s]+(?<![.,;!?؟۔،\)"\'])', re.IGNORECASE)
MENTION_PATTERN = re.compile(r'@[A-Za-z0-9_]+')
LEAKY = [r"sarcasm\w*", r"sarcastic\w*", r"beingsarcastic",
         r"satire\w*", r"racistjokes",
         r"طنزومزاح", r"طنز"]                 # only standard forms now
SARCASM_PATTERN = re.compile(r"#?(?:" + "|".join(LEAKY) + r")(?!\w)", re.IGNORECASE)
UNICODE_BOLD = re.compile(r'[\U0001D400-\U0001D7FF]+')

# Function to extract emojis into a new column and remove them from text
def extract_and_remove_emojis(text):
    text = str(text)
    # Find all emojis in the text
    found_emojis = "".join([char for char in text if char in emoji.EMOJI_DATA])
    # Remove emojis from the text
    cleaned_text = "".join(
        [char for char in text if char not in emoji.EMOJI_DATA]
    )
    return cleaned_text, found_emojis

# Function to process the hashtags with important content
def process_advanced_hashtags(text):
    # Find all hashtags
    hashtags = re.findall(r'#\w+', text)

    for tag in hashtags:
        clean_tag = tag.replace('#', '')

        # Check if it contains Urdu characters
        if re.search(r'[\u0600-\u06FF]', clean_tag):
            # It's Urdu: just remove the hash, leave it joined
            text = text.replace(tag, clean_tag)
        else:
            # It's English/Roman: Segment it using the library
            # segment() handles both CamelCase and all-lowercase brilliantly
            split_words = " ".join(segment(clean_tag))
            text = text.replace(tag, split_words)

    return text

def handle_bold_text(text):

    # 1. *word* or **word** → <EMPHASIS>word</EMPHASIS>
    text = re.sub(r'\*{1,2}([^*]+?)\*{1,2}', r'<EMPHASIS>\1</EMPHASIS>', text)

    # 2. Unicode bold runs → <EMPHASIS>...</EMPHASIS>
    text = UNICODE_BOLD.sub(lambda m: f"<EMPHASIS>{m.group(0)}</EMPHASIS>", text)

    return text

#### b. Text Preprocessing Pipeline

In [20]:
def text_preprocessing_pipeline(text):
    text = str(text)

    # normalizing arabic/urdu script
    text = unicodedata.normalize('NFKC', text)

    # adding <EMPHASIS></EMPHASIS> tags around bold words
    text = handle_bold_text(text)

    # Replacing URLs with the <URL> tags
    text = URL_PATTERN.sub('<URL>', text)

    # Removing all @mentions
    text = MENTION_PATTERN.sub('<USER>' , text)

    # Remove the terms that could risk leaking the target label
    text = SARCASM_PATTERN.sub("", text)

    # Preprocessing of the hashtags with the content we wanna keep
    text = process_advanced_hashtags(text)

    # replacing any remaining # symbols with whitespaces
    text = text.replace('#', '')

    # replacing all underscores with a white space
    text = text.replace('_', ' ')

    # Standardizing Urdu Punctuation to English equivalents
    text = text.replace('؟', '?').replace('۔', '.').replace('،', ',').replace('؛', ';').replace('٪', '%')

    # Remove hidden ZWNJ characters to prevent duplicate vocabulary tokens
    text = text.replace('\u200c', '')

    # Demojize Emojis INLINE
    # Converts 🙄 to "[rolling_eyes]" so the model reads it exactly where it occurred.
    text = emoji.demojize(text, delimiters=(" <", "> "))

    # converting all english text to lower-case
    text = text.lower()

    # Find all ?, ., ! marks
    found_punc = "".join(re.findall(r"[?.!]", text))

    # normalizing whitespace
    text = re.sub(r"\s+", " ", text).strip()

    # Remove all sorts of punctuation from the text
    # string.punctuation covers all standard symbols

    punct_to_remove = string.punctuation.replace("\\", "").replace("<", "").replace(">", "")

    translator = str.maketrans("", "", punct_to_remove)
    cleaned_text = text.translate(translator)

    return cleaned_text, found_punc

#### c. Function for One-Hot Encoding Each Column

In [21]:
from collections import Counter

def expand_element_counts(df, column_name):
    """
    Parses a column containing strings.
    - Preserves <tags> as whole unique elements (e.g., '<user_id>').
    - Treats all other non-space characters as individual elements.
    """
    def extract_and_tokenize(text):
        if pd.isna(text):
            return []

        # The change is here: [^<>\s] no longer has a '+' at the end.
        # This forces it to grab individual characters instead of chunks.
        return re.findall(r'<[^>]+>|[^<>\s]', str(text))

    # 1. Tokenize the string and count occurrences for each row
    counts_list = df[column_name].apply(lambda x: Counter(extract_and_tokenize(x))).tolist()

    # 2. Feed directly into a DataFrame constructor
    # 3. Fill missing elements with 0 and convert to integers, keeping original index
    counts_df = pd.DataFrame(counts_list, index=df.index).fillna(0).astype(int)

    # 4. Join the new columns back to the original DataFrame
    return pd.concat([df, counts_df], axis=1)

### vi. Dataset-1 (with individual emojis and punctuations as a separate features)

Contains the following columns:

* `is_sarcastic`
* `text` without emojis and punctuations

And the following columns contain the count of each element in a row:

* `!`
* `?`
* `.`
* A separate column for each demojized emoji (591 columns)

In [22]:
df1 = df.copy()

# Apply Emoji extraction
df1["text_no_emoji"], df1["emojis"] = zip(*df1["text"].apply(extract_and_remove_emojis))

# Apply Punctuation extraction on the emoji-cleaned text (or original text)
df1["cleaned_text"], df1["punctuations"] = zip(
    *df1["text_no_emoji"].apply(text_preprocessing_pipeline)
)

# Clean up intermediate column if you want
df1 = df1.drop(columns=["text_no_emoji"])
# Dropping the uncleaned `text` column
df1.drop(columns='text', inplace=True)
# Renaming `cleaned_text` to `text`
df1 = df1.rename(columns={'cleaned_text': 'text'})
# output
df1.columns

Index(['is_sarcastic', 'emojis', 'text', 'punctuations'], dtype='object')

In [23]:
# Changes 🔥 from :fire: to <fire>
df1['demojized'] = df1['emojis'].apply(
    lambda x: emoji.demojize(x, delimiters=("<", ">")) if pd.notna(x) else x
)
df1.drop(columns=['emojis'], inplace = True)

In [24]:
df1 = expand_element_counts(df1, 'demojized')
df1 = expand_element_counts(df1, 'punctuations')
df1.drop(columns=['demojized', 'punctuations'], inplace = True)
df1.columns

Index(['is_sarcastic', 'text', '<rolling_on_the_floor_laughing>',
       '<face_with_tears_of_joy>', '<neutral_face>', '<folded_hands>',
       '<smiling_face_with_sunglasses>', '<beaming_face_with_smiling_eyes>',
       '<broken_heart>', '<fire>',
       ...
       '<person_running_medium-light_skin_tone>', '<sparkle>', '<brain>',
       '<ATM_sign>', '<coin>', '<money_bag>', '<white_cane>', '.', '?', '!'],
      dtype='object', length=596)

In [25]:
df1.columns.tolist()

['is_sarcastic',
 'text',
 '<rolling_on_the_floor_laughing>',
 '<face_with_tears_of_joy>',
 '<neutral_face>',
 '<folded_hands>',
 '<smiling_face_with_sunglasses>',
 '<beaming_face_with_smiling_eyes>',
 '<broken_heart>',
 '<fire>',
 '<maple_leaf>',
 '<wilted_flower>',
 '<clapping_hands>',
 '<smiling_face_with_smiling_eyes>',
 '<grinning_squinting_face>',
 '<face_with_rolling_eyes>',
 '<loudly_crying_face>',
 '<smiling_face_with_heart-eyes>',
 '<rose>',
 '<winking_face_with_tongue>',
 '<thinking_face>',
 '<sad_but_relieved_face>',
 '<sweat_droplets>',
 '<red_heart>',
 '<victory_hand>',
 '<confused_face>',
 '<dog>',
 '<relieved_face>',
 '<smirking_face>',
 '<face_savoring_food>',
 '<squinting_face_with_tongue>',
 '<sparkling_heart>',
 '<pensive_face>',
 '<articulated_lorry>',
 '<enraged_face>',
 '<person_running_light_skin_tone>',
 '<male_sign>',
 '<grinning_face_with_sweat>',
 '<hundred_points>',
 '<speak-no-evil_monkey>',
 '<heart_suit>',
 '<grinning_face_with_smiling_eyes>',
 '<grinning_face_with_big_eyes>',
 '<person_facepalming>',
 '<smiling_cat_with_heart-eyes>',
 '<oncoming_fist>',
 '<two_hearts>',
 '<revolving_hearts>',
 '<victory_hand_light_skin_tone>',
 '<zipper-mouth_face>',
 '<persevering_face>',
 '<hibiscus>',
 '<leaf_fluttering_in_wind>',
 '<winking_face>',
 '<tulip>',
 '<person_raising_hand>',
 '<dragon>',
 '<dog_face>',
 '<slightly_smiling_face>',
 '<see-no-evil_monkey>',
 '<person_gesturing_OK>',
 '<female_sign>',
 '<recycling_symbol>',
 '<backhand_index_pointing_left>',
 '<person_beard>',
 '<OK_hand>',
 '<face_with_head-bandage>',
 '<man_light_skin_tone>',
 '<airplane>',
 '<cat_with_tears_of_joy>',
 '<flexed_biceps>',
 '<hand_with_fingers_splayed>',
 '<face_with_hand_over_mouth>',
 '<nerd_face>',
 '<check_mark>',
 '<thumbs_up>',
 '<thumbs_up_medium-light_skin_tone>',
 '<clapping_hands_medium-light_skin_tone>',
 '<smiling_face_with_halo>',
 '<grinning_face>',
 '<zany_face>',
 '<woman_dancing>',
 '<unamused_face>',
 '<page_with_curl>',
 '<bell>',
 '<balance_scale>',
 '<chains>',
 '<locked>',
 '<books>',
 '<new_moon_face>',
 '<cactus>',
 '<mushroom>',
 '<backhand_index_pointing_down>',
 '<speaker_medium_volume>',
 '<speaker_high_volume>',
 '<crying_face>',
 '<confounded_face>',
 '<grimacing_face>',
 '<hear-no-evil_monkey>',
 '<monkey>',
 '<face_screaming_in_fear>',
 '<seedling>',
 '<A_button_(blood_type)>',
 '<fallen_leaf>',
 '<man>',
 '<laptop>',
 '<butterfly>',
 '<shamrock>',
 '<sheaf_of_rice>',
 '<palm_tree>',
 '<deciduous_tree>',
 '<face_with_medical_mask>',
 '<man’s_shoe>',
 '<dizzy>',
 '<sleeping_face>',
 '<black_heart>',
 '<anguished_face>',
 '<pig_face>',
 '<smiling_face>',
 '<raised_fist>',
 '<green_heart>',
 '<check_mark_button>',
 '<angry_face>',
 '<face_with_tongue>',
 '<ghost>',
 '<horse>',
 '<bouquet>',
 '<counterclockwise_arrows_button>',
 '<expressionless_face>',
 '<snake>',
 '<star>',
 '<writing_hand_light_skin_tone>',
 '<palms_up_together_light_skin_tone>',
 '<red_exclamation_mark>',
 '<herb>',
 '<sunflower>',
 '<astonished_face>',
 '<face_blowing_a_kiss>',
 '<pencil>',
 '<writing_hand>',
 '<soap>',
 '<raised_fist_light_skin_tone>',
 '<index_pointing_up>',
 '<beating_heart>',
 '<popcorn>',
 '<flushed_face>',
 '<heart_with_ribbon>',
 '<tiger>',
 '<goat>',
 '<zebra>',
 '<backhand_index_pointing_right>',
 '<upside-down_face>',
 '<blue_heart>',
 '<palms_up_together>',
 '<raising_hands_light_skin_tone>',
 '<eyes>',
 '<thumbs_down>',
 '<goblin>',
 '<face_without_mouth>',
 '<smiling_face_with_horns>',
 '<person_running>',
 '<sleepy_face>',
 '<frowning_face>',
 '<heart_exclamation>',
 '<anger_symbol>',
 '<pile_of_poo>',
 '<crescent_moon>',
 '<milky_way>',
 '<disappointed_face>',
 '<crossed_swords>',
 '<black_flag>',
 '<skull_and_crossbones>',
 '<purple_heart>',
 '<person_golfing_light_skin_tone>',
 '<raising_hands>',
 '<birthday_cake>',
 '<performing_arts>',
 '<chicken>',
 '<egg>',
 '<disguised_face>',
 '<heart_with_arrow>',
 '<folded_hands_light_skin_tone>',
 '<raised_hand_medium-dark_skin_tone>',
 '<syringe>',
 '<thumbs_up_light_skin_tone>',
 '<face_with_steam_from_nose>',
 '<repeat_button>',
 '<yellow_heart>',
 '<folded_hands_dark_skin_tone>',
 '<person_walking>',
 '<cherry_blossom>',
 '<ogre>',
 '<banana>',
 '<person_gesturing_NO>',
 '<globe_showing_Americas>',
 '<key>',
 '<person_shrugging>',
 '<cat_face>',
 '<folded_hands_medium_skin_tone>',
 '<face_with_monocle>',
 '<fearful_face>',
 '<woman’s_boot>',
 '<police_officer>',
 '<bug>',
 '<tongue>',
 '<collision>',
 '<shushing_face>',
 '<reverse_button>',
 '<sun_with_face>',
 '<weary_cat>',
 '<kissing_face_with_closed_eyes>',
 '<smiling_face_with_open_hands>',
 '<trophy>',
 '<growing_heart>',
 '<sneezing_face>',
 '<black_small_square>',
 '<pleading_face>',
 '<globe_showing_Europe-Africa>',
 '<pizza>',
 '<mobile_phone>',
 '<sparkles>',
 '<clapping_hands_light_skin_tone>',
 '<ID_button>',
 '<cricket_game>',
 '<hiking_boot>',
 '<slightly_frowning_face>',
 '<love_letter>',
 '<copyright>',
 '<weary_face>',
 '<detective>',
 '<memo>',
 '<crown>',
 '<shooting_star>',
 '<hushed_face>',
 '<high_voltage>',
 '<full_moon_face>',
 '<pinching_hand>',
 '<face_with_open_mouth>',
 '<blossom>',
 '<moon_viewing_ceremony>',
 '<person_gesturing_OK_light_skin_tone>',
 '<cloud_with_rain>',
 '<face_with_raised_eyebrow>',
 '<downcast_face_with_sweat>',
 '<smiling_face_with_hearts>',
 '<frog>',
 '<raised_hand>',
 '<bus>',
 '<hatching_chick>',
 '<teacup_without_handle>',
 '<party_popper>',
 '<front-facing_baby_chick>',
 '<baby_chick>',
 '<pill>',
 '<bust_in_silhouette>',
 '<busts_in_silhouette>',
 '<kissing_face_with_smiling_eyes>',
 '<kissing_face>',
 '<cigarette>',
 '<tumbler_glass>',
 '<backhand_index_pointing_up>',
 '<rocket>',
 '<victory_hand_medium-light_skin_tone>',
 '<open_hands>',
 '<waving_hand>',
 '<person_facepalming_light_skin_tone>',
 '<worried_face>',
 '<kaaba>',
 '<fuel_pump>',
 '<backhand_index_pointing_down_light_skin_tone>',
 '<evergreen_tree>',
 '<raised_hand_light_skin_tone>',
 '<white_heart>',
 '<person_shrugging_light_skin_tone>',
 '<four_leaf_clover>',
 '<left_arrow_curving_right>',
 '<gem_stone>',
 '<person_shrugging_medium_skin_tone>',
 '<face_with_crossed-out_eyes>',
 '<heart_decoration>',
 '<purple_circle>',
 '<flexed_biceps_light_skin_tone>',
 '<person_tipping_hand>',
 '<pig>',
 '<horse_face>',
 '<yawning_face>',
 '<partying_face>',
 '<woozy_face>',
 '<musical_keyboard>',
 '<control_knobs>',
 '<person_tipping_hand_light_skin_tone>',
 '<ZZZ>',
 '<baby>',
 '<notebook>',
 '<watermelon>',
 '<jack-o-lantern>',
 '<grapes>',
 '<red_question_mark>',
 '<paw_prints>',
 '<cherries>',
 '<peach>',
 '<red_apple>',
 '<strawberry>',
 '<face_with_symbols_on_mouth>',
 '<postal_horn>',
 '<person_facepalming_dark_skin_tone>',
 '<money-mouth_face>',
 '<curry_rice>',
 '<high-heeled_shoe>',
 '<handshake>',
 '<dolphin>',
 '<cat_with_wry_smile>',
 '<princess>',
 '<cross_mark>',
 '<sun>',
 '<rainbow>',
 '<cucumber>',
 '<eggplant>',
 '<hot_pepper>',
 '<carrot>',
 '<helicopter>',
 '<potato>',
 '<tomato>',
 '<melon>',
 '<chestnut>',
 '<shallow_pan_of_food>',
 '<pot_of_food>',
 '<sparkler>',
 '<person_getting_massage>',
 '<small_orange_diamond>',
 '<loudspeaker>',
 '<envelope>',
 '<incoming_envelope>',
 '<envelope_with_arrow>',
 '<up-down_arrow>',
 '<hot_beverage>',
 '<person_cartwheeling>',
 '<police_car_light>',
 '<angry_face_with_horns>',
 '<folded_hands_medium-light_skin_tone>',
 '<water_buffalo>',
 '<musical_notes>',
 '<raised_back_of_hand>',
 '<anxious_face_with_sweat>',
 '<fairy>',
 '<skull>',
 '<person_pouting>',
 '<person_golfing>',
 '<yen_banknote>',
 '<OK_hand_light_skin_tone>',
 '<light_bulb>',
 '<person_gesturing_OK_medium_skin_tone>',
 '<small_blue_diamond>',
 '<woman_and_man_holding_hands>',
 '<wrapped_gift>',
 '<balloon>',
 '<middle_finger>',
 '<face_with_thermometer>',
 '<woman>',
 '<dove>',
 '<sports_medal>',
 '<2nd_place_medal>',
 '<1st_place_medal>',
 '<motorcycle>',
 '<safety_vest>',
 '<luggage>',
 '<baby_bottle>',
 '<teddy_bear>',
 '<tired_face>',
 '<person_bowing>',
 '<person_cartwheeling_light_skin_tone>',
 '<rooster>',
 '<tiger_face>',
 '<deer>',
 '<kiss_mark>',
 '<waving_hand_dark_skin_tone>',
 '<foot>',
 '<person_facepalming_medium-light_skin_tone>',
 '<house_with_garden>',
 '<ant>',
 '<down_arrow>',
 '<cat>',
 '<musical_note>',
 '<person_frowning>',
 '<first_quarter_moon>',
 '<bottle_with_popping_cork>',
 '<confetti_ball>',
 '<hammer>',
 '<black_nib>',
 '<leopard>',
 '<mosque>',
 '<chequered_flag>',
 '<star-struck>',
 '<bomb>',
 '<nail_polish_light_skin_tone>',
 '<writing_hand_medium-light_skin_tone>',
 '<alarm_clock>',
 '<military_medal>',
 '<eight-pointed_star>',
 '<dim_button>',
 '<bell_with_slash>',
 '<person>',
 '<exploding_head>',
 '<man_medium-dark_skin_tone>',
 '<red_circle>',
 '<two-thirty>',
 '<prohibited>',
 '<open_book>',
 '<closed_book>',
 '<full_moon>',
 '<new_moon>',
 '<orange_heart>',
 '<graduation_cap>',
 '<waxing_gibbous_moon>',
 '<waving_hand_light_skin_tone>',
 '<globe_showing_Asia-Australia>',
 '<shuffle_tracks_button>',
 '<grinning_cat_with_smiling_eyes>',
 '<beer_mug>',
 '<grinning_cat>',
 '<unlocked>',
 '<diamond_suit>',
 '<hamburger>',
 '<sandwich>',
 '<clown_face>',
 '<droplet>',
 '<water_wave>',
 '<sunrise_over_mountains>',
 '<mount_fuji>',
 '<anchor>',
 '<kitchen_knife>',
 '<Santa_Claus_light_skin_tone>',
 '<double_exclamation_mark>',
 '<face_vomiting>',
 '<sun_behind_small_cloud>',
 '<bookmark>',
 '<last_quarter_moon_face>',
 '<label>',
 '<love-you_gesture>',
 '<guide_dog>',
 '<backpack>',
 '<up-left_arrow>',
 '<dagger>',
 '<t-shirt>',
 '<jeans>',
 '<necktie>',
 '<running_shoe>',
 '<handbag>',
 '<reminder_ribbon>',
 '<lion>',
 '<green_book>',
 '<snowflake>',
 '<fountain>',
 '<drooling_face>',
 '<wolf>',
 '<guard>',
 '<folded_hands_medium-dark_skin_tone>',
 '<princess_medium-light_skin_tone>',
 '<french_fries>',
 '<wine_glass>',
 '<girl_light_skin_tone>',
 '<love-you_gesture_light_skin_tone>',
 '<prayer_beads>',
 '<hot_springs>',
 '<boy>',
 '<people_with_bunny_ears>',
 '<kissing_cat>',
 '<cowboy_hat_face>',
 '<megaphone>',
 '<locked_with_key>',
 '<locked_with_pen>',
 '<spade_suit>',
 '<raised_hand_dark_skin_tone>',
 '<thumbs_down_dark_skin_tone>',
 '<O_button_(blood_type)>',
 '<cityscape_at_dusk>',
 '<person_with_veil>',
 '<spiral_calendar>',
 '<woman_with_headscarf>',
 '<timer_clock>',
 '<camera>',
 '<bow_and_arrow>',
 '<link>',
 '<couple_with_heart>',
 '<bed>',
 '<saxophone>',
 '<automobile>',
 '<telephone>',
 '<person_in_tuxedo>',
 '<hammer_and_pick>',
 '<wrench>',
 '<pick>',
 '<tanabata_tree>',
 '<yo-yo>',
 '<footprints>',
 '<index_pointing_up_light_skin_tone>',
 '<ribbon>',
 '<medical_symbol>',
 '<rolled-up_newspaper>',
 '<house>',
 '<cup_with_straw>',
 '<oncoming_police_car>',
 '<trumpet>',
 '<studio_microphone>',
 '<poodle>',
 '<lying_face>',
 '<eject_button>',
 '<thumbs_up_medium_skin_tone>',
 '<mouse_face>',
 '<person_raising_hand_light_skin_tone>',
 '<tropical_drink>',
 '<man_dancing>',
 '<person_in_suit_levitating>',
 '<speaking_head>',
 '<coffin>',
 '<speech_balloon>',
 '<pig_nose>',
 '<BACK_arrow>',
 '<SOON_arrow>',
 '<clockwise_vertical_arrows>',
 '<up-right_arrow>',
 '<UP!_button>',
 '<money_with_wings>',
 '<crayon>',
 '<backhand_index_pointing_left_light_skin_tone>',
 '<glass_of_milk>',
 '<right_arrow_curving_down>',
 '<sunrise>',
 '<minus>',
 '<palms_up_together_medium-light_skin_tone>',
 '<Christmas_tree>',
 '<sign_of_the_horns>',
 '<fork_and_knife>',
 '<spoon>',
 '<pushpin>',
 '<eye>',
 '<victory_hand_medium_skin_tone>',
 '<unicorn>',
 '<flexed_biceps_medium_skin_tone>',
 '<thumbs_down_light_skin_tone>',
 '<fish_cake_with_swirl>',
 '<oncoming_taxi>',
 '<scorpion>',
 '<lizard>',
 '<cooking>',
 '<diamond_with_a_dot>',
 '<water_pistol>',
 '<first_quarter_moon_face>',
 '<glowing_star>',
 '<diya_lamp>',
 '<person_biking>',
 '<white_flower>',
 '<backhand_index_pointing_down_dark_skin_tone>',
 '<honeybee>',
 '<cyclone>',
 '<umbrella_with_rain_drops>',
 '<white_question_mark>',
 '<rosette>',
 '<crossed_fingers>',
 '<honey_pot>',
 '<no_smoking>',
 '<hollow_red_circle>',
 '<crying_cat>',
 '<OK_hand_medium-light_skin_tone>',
 '<person_facepalming_medium_skin_tone>',
 '<brown_heart>',
 '<duck>',
 '<orangutan>',
 '<owl>',
 '<person_blond_hair>',
 '<baby_angel>',
 '<nose>',
 '<night_with_stars>',
 '<person_bowing_light_skin_tone>',
 '<dashing_away>',
 '<no_one_under_eighteen>',
 '<person_shrugging_medium-light_skin_tone>',
 '<red_triangle_pointed_down>',
 '<chocolate_bar>',
 '<writing_hand_medium_skin_tone>',
 '<film_projector>',
 '<movie_camera>',
 '<guard_light_skin_tone>',
 '<person_juggling>',
 '<warning>',
 '<cooked_rice>',
 '<person_running_medium-light_skin_tone>',
 '<sparkle>',
 '<brain>',
 '<ATM_sign>',
 '<coin>',
 '<money_bag>',
 '<white_cane>',
 '.',
 '?',
 '!']

In [26]:
df1.head(2)

,is_sarcastic,text,<rolling_on_the_floor_laughing>,<face_with_tears_of_joy>,<neutral_face>,<folded_hands>,<smiling_face_with_sunglasses>,<beaming_face_with_smiling_eyes>,<broken_heart>,<fire>,...,<person_running_medium-light_skin_tone>,<sparkle>,<brain>,<ATM_sign>,<coin>,<money_bag>,<white_cane>,.,?,!
0,1,ہو لینے دے میری شادی فسادن ٹھیک ہے کوجی نہیں چاہیے,2,2,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,چل مہمانوں میں کھانا سرو کر چڑیل چاچی نوں دسدی آں میں,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
# Confirming that no hashtags are remaining

# Filter rows where the 'text' column contains a hashtag
hashtag_rows_df1 = df1[df1["text"].str.contains("#", na=False)]

# See how many rows have hashtags
print(f"Total rows with hashtags: {len(hashtag_rows_df1)}")

Total rows with hashtags: 0

#### Downloading Corpus1

In [37]:
from google.colab import files

text1 = df1['text']

with open('corpus1.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(text1) + '\n')

# Trigger the browser download
files.download('corpus1.txt')

#### Downloading df1 as Dataset1

In [ ]:
# Save the file first
df1.to_csv('dataset1.csv', index=False)

# Trigger the browser download
files.download('dataset1.csv')

### vii. Dataset-2 (emojis demojized and only punctuations as a separate individual features)

Contains the following columns:

* `is_sarcastic`
* `text`
  * contains no punctuation (the important ones are separated into their own columns)
  * contains demojized emojis i.e. laughing emoji converted into \<laughing emoji\> tag using `emoji` library

And the following three columns include the count of each element in a row:

* `!`
* `?`
* `.`

In [30]:
df2 = df.copy()

# Apply Punctuation extraction on the emoji-cleaned text (or original text)
df2["cleaned_text"], df2["punctuations"] = zip(
    *df2["text"].apply(text_preprocessing_pipeline)
)

# Dropping the uncleaned `text` column
df2.drop(columns='text', inplace=True)
# Renaming `cleaned_text` to `text`
df2 = df2.rename(columns={'cleaned_text': 'text'})
# output
df2.columns

Index(['is_sarcastic', 'text', 'punctuations'], dtype='object')

In [31]:
df2 = expand_element_counts(df2, 'punctuations')
df2.drop(columns=['punctuations'], inplace = True)
df2.columns

Index(['is_sarcastic', 'text', '.', '?', '!'], dtype='object')

In [32]:
df2.head(2)

,is_sarcastic,text,.,?,!
0,1,<rollingonthefloorlaughing> <facewithtearsofjoy> <facewithtearsofjoy> ہو لینے دے میری شادی فسادن ٹھیک ہے کوجی نہیں چاہیے <neutralface> <neutralface> <neutralface> <rollingonthefloorlaughing>,0,0,0
1,1,چل مہمانوں میں کھانا سرو کر چڑیل چاچی نوں دسدی آں میں <facewithtearsofjoy> <facewithtearsofjoy>,0,0,0

In [33]:
# Confirming that no hashtags are remaining

# Filter rows where the 'text' column contains a hashtag
hashtag_rows_df2 = df2[df2["text"].str.contains("#", na=False)]

# See how many rows have hashtags
print(f"Total rows with hashtags: {len(hashtag_rows_df2)}")

Total rows with hashtags: 0

#### Downloading Corpus2

In [39]:
text2 = df2['text']

with open('corpus2.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(text2) + '\n')

# Trigger the browser download
files.download('corpus2.txt')

#### Downloading df2 as Dataset2

In [35]:
# Save the file first
df2.to_csv('dataset2.csv', index=False)

# Trigger the browser download
files.download('dataset2.csv')